import type { ProjectDetail, ProjectSummary, SegmentDto } from "../tauri/projectApi";
import type { DocxExportMode } from "../tauri/exportDocxApi";
import type { DeliveryDocxExportRequest } from "./useExportController";
import type { SegmentOverlapPolicy } from "../utils/segmentTimeRange";
import type { SegmentRefineDialogState } from "./useSegmentRefineController";
import type { LexiconProofreadDialogState } from "./useLexiconProofreadController";
import type { AutoPunctuateDialogState } from "./useAutoPunctuateController";
import type { FindReplaceDialogState } from "./useFindReplaceController";
import type { CorrectionRulesDialogState } from "./useCorrectionRulesController";
import type { CorrectSuggestionsDialogState } from "./useCorrectSuggestionsController";
import type { GlossaryLearnPromptDialogState } from "./useGlossaryLearnPromptController";
import type { CorrectSuggestion } from "../services/editor/correctSuggestions";
import type { GlossaryLearnPromptRow } from "../tauri/correctionApi";
import type { BusyReason } from "./useProjectCrudController";

export type { BusyReason };

export interface ProjectLifecycleApi {
  projects: ProjectSummary[];
  current: ProjectDetail | null;
  currentFileId: string | null;
  segments: SegmentDto[];
  selectedIdx: number;
  setSelectedIdx: React.Dispatch<React.SetStateAction<number>>;
  audioSrc: string | null;
  error: string;
  busy: boolean;
  busyReason: BusyReason | null;
  newName: string;
  setNewName: React.Dispatch<React.SetStateAction<string>>;
  pickedPath: string | null;
  transcribeHints: string[];
  transcribeProgress: import("./transcribePreviewState").TranscribeProgress | null;
  transcribeCancelling: boolean;
  transcribePreviewActive: boolean;
  transcribeOverwriteDialogOpen: boolean;
  transcribeOverwriteSegmentCount: number;
  transcribeVocabularyPreflightLines: string[];
  refreshProjects: () => Promise<void>;
  pickAudio: () => Promise<void>;
  clearPickedAudio: () => void;
  createProject: () => Promise<void>;
  createEmptyProject: () => Promise<void>;
  createProjectFromText: () => Promise<void>;
  loadProject: (id: string) => Promise<void>;
  openFile: (fileId: string) => Promise<void>;
  openLastEditorWorkspace: () => Promise<void>;
  closeFile: () => void;
  closeProject: () => void;
  refreshCurrentProject: () => Promise<void>;
  runTranscribe: () => Promise<void>;
  cancelTranscribe: () => Promise<void>;
  confirmTranscribeOverwrite: () => void;
  cancelTranscribeOverwrite: () => void;
  saveSegments: (options?: {
    quiet?: boolean;
    countHits?: boolean;
    explicitPairs?: import("../tauri/fileApi").CorrectionExplicitPair[];
  }) => Promise<boolean>;
  /** Cmd/Ctrl+Enter：落笔保存未提交正文并选中下一语段。 */
  confirmSegmentEditAndAdvance: (segmentIdx: number) => Promise<boolean>;
  manualCorrectionMemoryDialog: import("./useManualCorrectionMemoryDialog").ManualCorrectionMemoryDialogState;
  openManualCorrectionMemoryDialog: (wrong: string) => void;
  closeManualCorrectionMemoryDialog: () => void;
  setManualCorrectionRight: (right: string) => void;
  setManualCorrectionAlsoGlossary: (value: boolean) => void;
  confirmManualCorrectionMemory: () => void;
  canConfirmSegmentEdit: (segmentIdx: number) => boolean;
  getSavedSnapshot: () => import("../tauri/projectApi").SegmentDto[];
  editorSpansForText: (text: string) => import("../services/editor/findCorrectableSpans").CorrectableSpan[];
  editorCorrectPopover: import("./useEditorSegmentCorrectPopover").SegmentCorrectPopoverState | null;
  editorCorrectPopoverSuggestions: import("../services/editor/correctSuggestions").CorrectSuggestion[];
  openEditorCorrectPopover: (
    segmentIdx: number,
    span: import("../services/editor/findCorrectableSpans").CorrectableSpan,
    clientX: number,
    clientY: number,
  ) => void;
  closeEditorCorrectPopover: () => void;
  applyEditorInlineCorrection: (item: import("../services/editor/correctSuggestions").CorrectSuggestion) => void;
  autoSaveFooterStatus: import("./useAutoSaveSegments").AutoSaveFooterStatus;
  deleteProject: (id: string, options?: { skipBrowserConfirm?: boolean }) => Promise<void>;
  exportTxt: () => Promise<void>;
  exportSrt: () => Promise<void>;
  exportDocx: (mode: DocxExportMode) => Promise<void>;
  exportDeliveryDocx: (request: DeliveryDocxExportRequest) => Promise<void>;
  exportDiagnosticBundle: () => Promise<void>;
  exportProjectBundle: () => Promise<void>;
  importProjectBundle: () => Promise<void>;
  openAppDataFolder: () => Promise<void>;
  applyDetail: (d: ProjectDetail) => void;
  setError: React.Dispatch<React.SetStateAction<string>>;
  beginBusy: (reason: BusyReason) => void;
  endBusy: () => void;

  undo: () => void;
  redo: () => void;
  updateSegmentText: (idx: number, text: string) => void;
  updateSegmentTime: (idx: number, field: "start_sec" | "end_sec", value: number) => void;
  updateSegmentBounds: (idx: number, startSec: number, endSec: number, phase?: "live" | "commit") => void;
  splitAtSelection: () => void;
  splitAtPlayhead: (timeSec: number) => void;
  mergeWithNext: () => void;
  mergeWithPrev: () => void;
  mergeWithNextAt: (idx: number) => void;
  mergeWithPrevAt: (idx: number) => void;
  deleteSegmentAt: (idx: number) => void;
  insertSegmentAfter: (idx: number, mediaDurationSec?: number) => void;
  insertSegmentFromTimeRange: (
    startSec: number,
    endSec: number,
    mediaDurationSec?: number,
    policy?: SegmentOverlapPolicy,
  ) => void;
  flushSegmentTextDrafts: () => void;
  canAutoPunctuate: boolean;
  autoPunctuateBlockReason: string | null;
  autoPunctuateDialog: AutoPunctuateDialogState;
  requestAutoPunctuate: () => void;
  confirmAutoPunctuateConsent: () => void;
  confirmAutoPunctuateWriteback: () => void;
  cancelAutoPunctuate: () => void;
  canRefineSegments: boolean;
  segmentRefineBlockReason: string | null;
  segmentRefineDialog: SegmentRefineDialogState;
  requestSegmentRefine: () => void;
  confirmSegmentRefineConsent: () => void;
  confirmSegmentRefineWriteback: () => void;
  cancelSegmentRefine: () => void;
  canLexiconProofread: boolean;
  lexiconProofreadBlockReason: string | null;
  lexiconProofreadDialog: LexiconProofreadDialogState;
  requestLexiconProofread: () => void;
  confirmLexiconProofreadConsent: () => void;
  confirmLexiconProofreadWriteback: () => void;
  setLexiconAcceptRulesOnWriteback: (value: boolean) => void;
  toggleLexiconProofreadOp: (index: number, selected: boolean) => void;
  setAllLexiconProofreadOps: (selected: boolean) => void;
  cancelLexiconProofread: () => void;
  canFindReplace: boolean;
  findReplaceBlockReason: string | null;
  findReplaceDialog: FindReplaceDialogState;
  openFindReplace: (initialFind?: string, initialReplace?: string) => void;
  closeFindReplace: () => void;
  setFindReplaceFindText: (value: string) => void;
  setFindReplaceReplaceText: (value: string) => void;
  findReplaceRunSearch: () => void;
  findReplaceSelectMatch: (globalIndex: number) => void;
  findReplaceGoNext: () => void;
  findReplaceGoPrev: () => void;
  findReplaceCurrent: () => void;
  findReplaceRequestReplaceAll: () => void;
  findReplaceConfirmReplaceAll: () => Promise<void>;
  findReplaceCancelReplaceAllPreview: () => void;
  findReplaceEditorHighlight: { segmentIdx: number; charStart: number; charEnd: number } | null;
  findReplaceReplaceAndNext: () => void;
  canApplyCorrectionRules: boolean;
  correctionRulesBlockReason: string | null;
  correctionRulesDialog: CorrectionRulesDialogState;
  requestCorrectionRules: () => void;
  confirmCorrectionRulesWriteback: () => void | Promise<void>;
  cancelCorrectionRules: () => void;
  canCorrectSuggestions: boolean;
  correctSuggestionsBlockReason: string | null;
  correctSuggestionsDialog: CorrectSuggestionsDialogState;
  requestCorrectSuggestions: (selectionOverride?: string) => void;
  applyCorrectSuggestion: (item: CorrectSuggestion) => void;
  cancelCorrectSuggestions: () => void;
  openFindReplaceForCorrectSelection: () => void;
  glossaryLearnDialog: GlossaryLearnPromptDialogState;
  dismissGlossaryLearnPrompt: (row: GlossaryLearnPromptRow) => void;
  confirmAddToGlossary: (row: GlossaryLearnPromptRow) => void;
  closeGlossaryLearnPrompt: () => void;
  restoreEditorFromEditLog: (editLogId: number) => Promise<void>;
  bumpLlmRuntimeChanged: () => void;
  closeGateOpen: boolean;
  closeGateIntent: "app-quit" | "navigate";
  stayAfterCloseAttempt: () => void;
  discardUnsavedAndClose: () => void;
  saveAndClose: () => void;
}
