import type { ProjectLifecycleApi } from "./ProjectLifecycleApi";
import { deriveTranscribePreviewActive } from "./projectLifecycleFacades";
import { mapEditorToolsLifecycleFields } from "./projectLifecycleEditorToolsReturn";
import type { ProjectLifecycleReturnInput } from "./projectLifecycleReturnTypes";

export type { ProjectLifecycleReturnInput } from "./projectLifecycleReturnTypes";

/** 将子 controller 字段组装为 ProjectLifecycleApi return。 */
export function buildProjectLifecycleReturn(input: ProjectLifecycleReturnInput): ProjectLifecycleApi {
  const {
    projects,
    current,
    currentFileId,
    segments,
    selectedIdx,
    setSelectedIdx,
    audioSrc,
    audioStoragePath,
    error,
    busy,
    busyReason,
    newName,
    setNewName,
    pickedPath,
    refreshProjects,
    pickAudio,
    clearPickedAudio,
    refreshCurrentProject,
    openAppDataFolder,
    applyDetail,
    setError,
    beginBusy,
    endBusy,
    selectedIdxRef,
    closeGateFacade,
    exportFacade,
    transcribeJob,
    editorTools,
    crud,
    saveController,
    autoSave,
    dirty,
    mutations,
    segmentSelection,
    clearMultiSelectionWithChrome,
    segmentDeleteConfirm,
    glossaryLearn,
    manualCorrectionMemory,
    importDuplicate,
    fileMutation,
    projectMutation,
    segmentAnnotation,
    segmentFreeze,
    batchTranscribe,
  } = input;

  const {
    saveSegments,
    confirmSegmentEditAndAdvance,
    markSegmentFinalized,
    restoreEditorFromEditLog,
  } = saveController;

  return {
    projects,
    current,
    currentFileId,
    segments,
    selectedIdx,
    selectedIdxRef,
    setSelectedIdx,
    audioSrc,
    audioStoragePath,
    error,
    busy,
    busyReason,
    newName,
    setNewName,
    pickedPath,
    transcribeHints: transcribeJob.transcribeHints,
    transcribeFailureDiag: transcribeJob.transcribeFailureDiag,
    setTranscribeFailureDiag: transcribeJob.setTranscribeFailureDiag,
    transcribeProgress: transcribeJob.transcribeProgress,
    transcribeCancelling: transcribeJob.transcribeCancelling,
    transcribePreviewActive: deriveTranscribePreviewActive(busy, busyReason),
    transcribeStartDialogOpen: transcribeJob.transcribeStartDialogOpen,
    transcribeStartHasExistingText: transcribeJob.transcribeStartHasExistingText,
    transcribeOverwriteSegmentCount: transcribeJob.overwriteSegmentCount,
    transcribeVocabularyPreflightLines: transcribeJob.transcribeVocabularyPreflightLines,
    transcribeSource: transcribeJob.transcribeSource,
    setTranscribeSource: transcribeJob.setTranscribeSource,
    onlineTranscribeReady: transcribeJob.onlineTranscribeReady,
    refreshProjects,
    pickAudio,
    clearPickedAudio,
    createProject: crud.createProject,
    createEmptyProject: crud.createEmptyProject,
    createProjectFromText: crud.createProjectFromText,
    ...closeGateFacade,
    refreshCurrentProject,
    restoreEditorFromEditLog,
    runTranscribe: transcribeJob.requestTranscribe,
    cancelTranscribe: transcribeJob.cancelTranscribe,
    confirmTranscribeStart: transcribeJob.confirmTranscribeStart,
    cancelTranscribeStart: transcribeJob.cancelTranscribeStart,
    saveSegments,
    confirmSegmentEditAndAdvance,
    markSegmentFinalized,
    getSavedSnapshot: dirty.getSavedSnapshot,
    autoSaveFooterStatus: autoSave.autoSaveFooterStatus,
    ...mapEditorToolsLifecycleFields(editorTools),
    deleteProject: crud.deleteProject,
    ...exportFacade,
    openAppDataFolder,
    applyDetail,
    setError,
    beginBusy,
    endBusy,
    undo: mutations.undo,
    redo: mutations.redo,
    updateSegmentText: mutations.updateSegmentText,
    updateSegmentTime: mutations.updateSegmentTime,
    updateSegmentBounds: mutations.updateSegmentBounds,
    splitAtSelection: () => mutations.splitAtSelection(selectedIdxRef.current),
    splitAtPlayhead: mutations.splitAtPlayhead,
    mergeWithNext: () => {
      mutations.mergeWithNext(selectedIdxRef.current);
    },
    mergeWithPrev: () => {
      mutations.mergeWithPrev(selectedIdxRef.current);
    },
    mergeWithNextAt: mutations.mergeWithNextAt,
    mergeWithPrevAt: mutations.mergeWithPrevAt,
    mergeSegmentRange: mutations.mergeSegmentRange,
    deleteSegmentAt: segmentDeleteConfirm.requestDeleteSegmentAt,
    requestDeleteSelection: segmentDeleteConfirm.requestDeleteSelection,
    requestDeleteSelectedIndices: segmentDeleteConfirm.requestDeleteSelectedIndices,
    pendingDeleteCount: segmentDeleteConfirm.pendingDeleteCount,
    segmentDeleteConfirmOpen: segmentDeleteConfirm.segmentDeleteConfirmOpen,
    confirmDeleteSegment: segmentDeleteConfirm.confirmDeleteSegment,
    cancelDeleteSegment: segmentDeleteConfirm.cancelDeleteSegment,
    selectionLo: segmentSelection.selectionLo,
    selectionHi: segmentSelection.selectionHi,
    selectionRangeAnchorIdx: segmentSelection.selectionRangeAnchorIdx,
    selectionCount: segmentSelection.selectionCount,
    isMultiSegmentSelection: segmentSelection.isMultiSegmentSelection,
    isContiguousSelection: segmentSelection.isContiguousSelection,
    selectedIndices: segmentSelection.selectedIndices,
    selectedIndicesArray: segmentSelection.selectedIndicesArray,
    isIndexInSelection: segmentSelection.isIndexInSelection,
    selectSegmentAt: segmentSelection.selectSegmentAt,
    selectSegmentRange: segmentSelection.selectSegmentRange,
    selectSegmentIndices: segmentSelection.selectSegmentIndices,
    clearMultiSelection: clearMultiSelectionWithChrome,
    insertSegmentAfter: mutations.insertSegmentAfter,
    insertSegmentFromTimeRange: mutations.insertSegmentFromTimeRange,
    flushSegmentTextDrafts: mutations.flushSegmentTextDrafts,
    glossaryLearnDialog: glossaryLearn.glossaryLearnDialog,
    dismissGlossaryLearnPrompt: glossaryLearn.dismissGlossaryLearnPrompt,
    confirmAddToGlossary: (row) => {
      void glossaryLearn.confirmAddToGlossary(row);
    },
    closeGlossaryLearnPrompt: glossaryLearn.closeGlossaryLearnPrompt,
    manualCorrectionMemoryDialog: manualCorrectionMemory.manualCorrectionMemoryDialog,
    openManualCorrectionMemoryDialog: manualCorrectionMemory.openManualCorrectionMemoryDialog,
    closeManualCorrectionMemoryDialog: manualCorrectionMemory.closeManualCorrectionMemoryDialog,
    setManualCorrectionRight: manualCorrectionMemory.setManualCorrectionRight,
    setManualCorrectionAlsoGlossary: manualCorrectionMemory.setManualCorrectionAlsoGlossary,
    confirmManualCorrectionMemory: () => {
      void manualCorrectionMemory.confirmManualCorrectionMemory();
    },
    duplicateImportConfirmOpen: importDuplicate.duplicateImportConfirmOpen,
    duplicateImportChecking: importDuplicate.duplicateImportChecking,
    duplicateImportCheck: importDuplicate.duplicateImportCheck,
    cancelDuplicateImport: importDuplicate.cancelDuplicateImport,
    openExistingDuplicateImport: importDuplicate.openExistingDuplicateImport,
    confirmDuplicateImportCopy: importDuplicate.confirmDuplicateImportCopy,
    attachImportTargetOpen: importDuplicate.attachImportTargetOpen,
    attachImportTargetCandidates: importDuplicate.attachImportTargetCandidates,
    attachImportTargetStem: importDuplicate.attachImportTargetStem,
    cancelAttachImportTarget: importDuplicate.cancelAttachImportTarget,
    confirmAttachImportTarget: importDuplicate.confirmAttachImportTarget,
    importFileToProject: importDuplicate.importFileToProject,
    pickAndImportFileToProject: importDuplicate.pickAndImportFileToProject,
    pickAndImportAudioPathsToProject: importDuplicate.pickAndImportAudioPathsToProject,
    batchQueueOpen: batchTranscribe.batchQueueOpen,
    batchQueueItems: batchTranscribe.batchQueueItems,
    batchTranscribeRunning: batchTranscribe.batchTranscribeRunning,
    batchTranscribableCount: batchTranscribe.batchTranscribableCount,
    canStartBatchTranscribe: batchTranscribe.canStartBatchTranscribe,
    startBatchTranscribe: async () => {
      await batchTranscribe.startBatchTranscribe();
    },
    cancelBatchTranscribe: () => batchTranscribe.cancelBatchTranscribe(),
    closeBatchQueueDialog: batchTranscribe.closeBatchQueueDialog,
    renamingProjectFileId: fileMutation.renamingProjectFileId,
    renameProjectFileDraft: fileMutation.renameProjectFileDraft,
    setRenameProjectFileDraft: fileMutation.setRenameProjectFileDraft,
    beginRenameProjectFile: fileMutation.beginRenameProjectFile,
    cancelRenameProjectFile: fileMutation.cancelRenameProjectFile,
    commitRenameProjectFile: () => void fileMutation.commitRenameProjectFile(),
    pendingProjectFileDelete: fileMutation.pendingProjectFileDelete,
    requestDeleteProjectFile: fileMutation.requestDeleteProjectFile,
    cancelDeleteProjectFile: fileMutation.cancelDeleteProjectFile,
    confirmDeleteProjectFile: () => void fileMutation.confirmDeleteProjectFile(),
    pendingProjectFileMove: fileMutation.pendingProjectFileMove,
    requestMoveProjectFile: fileMutation.requestMoveProjectFile,
    moveProjectFileNow: (args) => void fileMutation.moveProjectFileNow(args),
    cancelMoveProjectFile: fileMutation.cancelMoveProjectFile,
    confirmMoveProjectFile: () => void fileMutation.confirmMoveProjectFile(),
    pendingProjectFileCopy: fileMutation.pendingProjectFileCopy,
    requestCopyProjectFile: fileMutation.requestCopyProjectFile,
    cancelCopyProjectFile: fileMutation.cancelCopyProjectFile,
    confirmCopyProjectFile: () => void fileMutation.confirmCopyProjectFile(),
    revealProjectLocation: (projectId) => void fileMutation.revealProjectLocation(projectId),
    revealFileLocation: (fileId) => void fileMutation.revealFileLocation(fileId),
    isRenamingProject: projectMutation.isRenamingProject,
    renamingProjectId: projectMutation.renamingProjectId,
    renameProjectDraft: projectMutation.renameProjectDraft,
    setRenameProjectDraft: projectMutation.setRenameProjectDraft,
    beginRenameProject: projectMutation.beginRenameProject,
    cancelRenameProject: projectMutation.cancelRenameProject,
    commitRenameProject: () => void projectMutation.commitRenameProject(),
    projectMetadataDialogOpen: projectMutation.projectMetadataDialogOpen,
    projectMetadataAfterCreate: projectMutation.projectMetadataAfterCreate,
    openProjectMetadataDialog: projectMutation.openProjectMetadataDialog,
    closeProjectMetadataDialog: projectMutation.closeProjectMetadataDialog,
    saveProjectMetadata: (metadata) => void projectMutation.saveProjectMetadata(metadata),
    pendingProjectDelete: projectMutation.pendingProjectDelete,
    requestDeleteProject: projectMutation.requestDeleteProject,
    cancelDeleteProject: projectMutation.cancelDeleteProject,
    confirmDeleteProject: () => void projectMutation.confirmDeleteProject(),
    segmentAnnotationDialog: segmentAnnotation.segmentAnnotationDialog,
    segmentAnnotationSaving: segmentAnnotation.segmentAnnotationSaving,
    openSegmentAnnotationDialog: segmentAnnotation.openSegmentAnnotationDialog,
    closeSegmentAnnotationDialog: segmentAnnotation.closeSegmentAnnotationDialog,
    setSegmentAnnotationDraft: segmentAnnotation.setSegmentAnnotationDraft,
    saveSegmentAnnotation: segmentAnnotation.saveSegmentAnnotation,
    clearSegmentAnnotation: segmentAnnotation.clearSegmentAnnotation,
    toggleSegmentFrozen: segmentFreeze.toggleSegmentFrozen,
  };
}
