import type { CloseGateLifecycleFacade, ExportLifecycleFacade } from "./projectLifecycleFacades";
import type { useProjectEditorToolsController } from "./useProjectEditorToolsController";
import type { useTranscribeJobController } from "./useTranscribeJobController";
import type { useSegmentMutationController } from "./useSegmentMutationController";
import type { useSegmentSelectionController } from "./useSegmentSelectionController";
import type { useSegmentDeleteConfirmController } from "./useSegmentDeleteConfirmController";
import type { useGlossaryLearnPromptController } from "./useGlossaryLearnPromptController";
import type { useManualCorrectionMemoryDialog } from "./useManualCorrectionMemoryDialog";
import type { useProjectImportDuplicateController } from "./useProjectImportDuplicateController";
import type { useProjectFileMutationController } from "./useProjectFileMutationController";
import type { useProjectMutationController } from "./useProjectMutationController";
import type { useSegmentAnnotationController } from "./useSegmentAnnotationController";
import type { useBatchTranscribeQueueController } from "./useBatchTranscribeQueueController";
import type { useProjectCrudController } from "./useProjectCrudController";
import type { useProjectSaveController } from "./useProjectSaveController";
import type { useAutoSaveSegments } from "./useAutoSaveSegments";
import type { useSegmentDirtyState } from "./useSegmentDirtyState";
import type { BusyReason } from "./useProjectCrudController";
import type { ProjectDetail, ProjectSummary, SegmentDto } from "../tauri/projectApi";

type EditorTools = ReturnType<typeof useProjectEditorToolsController>;
type TranscribeJob = ReturnType<typeof useTranscribeJobController>;
type Mutations = ReturnType<typeof useSegmentMutationController>;
type SegmentSelection = ReturnType<typeof useSegmentSelectionController>;
type SegmentDeleteConfirm = ReturnType<typeof useSegmentDeleteConfirmController>;
type GlossaryLearn = ReturnType<typeof useGlossaryLearnPromptController>;
type ManualCorrectionMemory = ReturnType<typeof useManualCorrectionMemoryDialog>;
type ImportDuplicate = ReturnType<typeof useProjectImportDuplicateController>;
type FileMutation = ReturnType<typeof useProjectFileMutationController>;
type ProjectMutation = ReturnType<typeof useProjectMutationController>;
type SegmentAnnotation = ReturnType<typeof useSegmentAnnotationController>;
type BatchTranscribe = ReturnType<typeof useBatchTranscribeQueueController>;
type Crud = ReturnType<typeof useProjectCrudController>;
type SaveController = ReturnType<typeof useProjectSaveController>;
type AutoSave = ReturnType<typeof useAutoSaveSegments>;
type Dirty = ReturnType<typeof useSegmentDirtyState>;

export type ProjectLifecycleReturnInput = {
  projects: ProjectSummary[];
  current: ProjectDetail | null;
  currentFileId: string | null;
  segments: SegmentDto[];
  selectedIdx: number;
  setSelectedIdx: React.Dispatch<React.SetStateAction<number>>;
  audioSrc: string | null;
  audioStoragePath: string | null;
  error: string;
  busy: boolean;
  busyReason: BusyReason | null;
  newName: string;
  setNewName: React.Dispatch<React.SetStateAction<string>>;
  pickedPath: string | null;
  refreshProjects: () => Promise<void>;
  pickAudio: () => Promise<void>;
  clearPickedAudio: () => void;
  refreshCurrentProject: () => Promise<void>;
  openAppDataFolder: () => Promise<void>;
  applyDetail: (detail: ProjectDetail) => void;
  setError: React.Dispatch<React.SetStateAction<string>>;
  beginBusy: (reason: BusyReason) => void;
  endBusy: () => void;
  selectedIdxRef: React.MutableRefObject<number>;
  getCurrentSegmentsSnapshot: () => SegmentDto[];
  closeGateFacade: CloseGateLifecycleFacade;
  exportFacade: ExportLifecycleFacade;
  transcribeJob: TranscribeJob;
  editorTools: EditorTools;
  crud: Crud;
  saveController: SaveController;
  autoSave: AutoSave;
  dirty: Dirty;
  mutations: Mutations;
  segmentSelection: SegmentSelection;
  segmentDeleteConfirm: SegmentDeleteConfirm;
  glossaryLearn: GlossaryLearn;
  manualCorrectionMemory: ManualCorrectionMemory;
  importDuplicate: ImportDuplicate;
  fileMutation: FileMutation;
  projectMutation: ProjectMutation;
  segmentAnnotation: SegmentAnnotation;
  batchTranscribe: BatchTranscribe;
};
