import { useCallback, useRef } from "react";
import { useAsrBridgeController, type AsrHealthState } from "./useAsrBridgeController";
import { funasrManualSetupCommands, parseAsrHealthJson } from "../services/asr/asrHealthParse";
import { useAsrSetupController } from "./useAsrSetupController";
import { useProjectLifecycleController, type BusyReason } from "./useProjectLifecycleController";
import { refreshLocalAsrDiagnostics } from "./refreshLocalAsrDiagnostics";
import { useEnvironmentCapabilitySync } from "../hooks/useEnvironmentCapabilitySync";
import { getEnvironmentCapabilityBlockReason } from "../services/environmentCapabilityCoordinator";
import {
  isLocalLoopbackLlmConfig,
  readLlmRuntimeConfigFromStorage,
} from "../services/postprocess/postprocessRuntimeContract";
import { refreshLlmOllamaDetect } from "../services/llm/llmEnvRuntimeStore";

export type { AsrHealthState, BusyReason };
export type BusyPack = { busy: boolean; reason: BusyReason | null };
export type ProjectControllerApi = ReturnType<typeof useProjectController>;

export { parseAsrHealthJson, funasrManualSetupCommands };

export function useProjectController() {
  const refreshSetupDiagnoseRef = useRef<
    ((options?: { resetSteps?: boolean; touchUi?: boolean }) => Promise<unknown>) | null
  >(null);

  const asr = useAsrBridgeController({
    refreshEnvironmentDiagnostics: async () => {
      const refreshSetup = refreshSetupDiagnoseRef.current;
      if (!refreshSetup) return;
      await refreshSetup({ resetSteps: false, touchUi: false });
    },
  });
  const { refreshAsrHealth, refreshAsrModelCacheInfo } = asr;
  const refreshAsrRuntimeInfo = useCallback(async () => {
    await refreshLocalAsrDiagnostics({
      refreshAsrHealth,
      refreshAsrModelCacheInfo,
      refreshSetupDiagnose: refreshSetupDiagnoseRef.current ?? undefined,
    });
  }, [refreshAsrHealth, refreshAsrModelCacheInfo]);
  const asrSetup = useAsrSetupController({
    refreshAsrHealth: asr.refreshAsrHealth,
    refreshAsrRuntimeInfo,
    prepareDefaultFunasrModel: asr.prepareDefaultFunasrModel,
    getSetupSelection: () => ({
      selectedHubModelId: asr.localAsrModelCatalog.selectedHubModelId,
      catalogStatus: asr.localAsrModelCatalog.catalogStatus,
    }),
  });
  refreshSetupDiagnoseRef.current = asrSetup.refreshSetupDiagnose;

  const localTranscribePreflight = useCallback(
    () => getEnvironmentCapabilityBlockReason() ?? asr.asrPresentation.blockReason,
    [asr.asrPresentation],
  );

  const lifecycle = useProjectLifecycleController(
    localTranscribePreflight,
    asr.sttOnlineRuntimeEpoch,
  );

  useEnvironmentCapabilitySync({
    projectId: lifecycle.current?.id,
    refreshAsrHealth,
    refreshAsrModelCacheInfo,
    refreshSetupDiagnose: asrSetup.refreshSetupDiagnose,
    bumpLlmRuntimeChanged: lifecycle.bumpLlmRuntimeChanged,
    bumpSttOnlineRuntimeChanged: asr.bumpSttOnlineRuntimeChanged,
    refreshLlmOllamaDetect: async () => {
      const config = readLlmRuntimeConfigFromStorage();
      if (isLocalLoopbackLlmConfig(config)) {
        await refreshLlmOllamaDetect();
      }
    },
    getCacheOverlay: () => ({
      desktopModelsRoot: asr.asrModelCacheInfo?.models_root ?? null,
      asrModelCacheBytes: asr.asrModelCacheInfo?.total_bytes ?? 0,
    }),
    getAsrPresentationOverlay: () => ({
      selectedHubModelId: asr.localAsrModelCatalog.selectedHubModelId,
      catalogStatus: asr.localAsrModelCatalog.catalogStatus,
      sidecarAsyncTranscribeCapable: asr.localAsrModelCatalog.sidecarAsyncTranscribeCapable,
      prepareModelBusy: asr.prepareModelBusy,
      prepareModelCancelling: asr.prepareModelCancelling,
      prepareModelProgress: asr.prepareModelProgress,
    }),
  });

  return {
    // Lifecycle
    projects: lifecycle.projects,
    current: lifecycle.current,
    currentFileId: lifecycle.currentFileId,
    segments: lifecycle.segments,
    selectedIdx: lifecycle.selectedIdx,
    setSelectedIdx: lifecycle.setSelectedIdx,
    audioSrc: lifecycle.audioSrc,
    audioStoragePath: lifecycle.audioStoragePath,
    error: lifecycle.error,
    setError: lifecycle.setError,
    busy: lifecycle.busy,
    busyReason: lifecycle.busyReason,
    newName: lifecycle.newName,
    setNewName: lifecycle.setNewName,
    pickedPath: lifecycle.pickedPath,
    transcribeHints: lifecycle.transcribeHints,
    transcribeFailureDiag: lifecycle.transcribeFailureDiag,
    setTranscribeFailureDiag: lifecycle.setTranscribeFailureDiag,
    transcribeProgress: lifecycle.transcribeProgress,
    transcribeCancelling: lifecycle.transcribeCancelling,
    transcribePreviewActive: lifecycle.transcribePreviewActive,
    transcribeOverwriteSegmentCount: lifecycle.transcribeOverwriteSegmentCount,
    transcribeVocabularyPreflightLines: lifecycle.transcribeVocabularyPreflightLines,
    transcribeSource: lifecycle.transcribeSource,
    setTranscribeSource: lifecycle.setTranscribeSource,
    onlineTranscribeReady: lifecycle.onlineTranscribeReady,
    refreshProjects: lifecycle.refreshProjects,
    pickAudio: lifecycle.pickAudio,
    clearPickedAudio: lifecycle.clearPickedAudio,
    createProject: lifecycle.createProject,
    createEmptyProject: lifecycle.createEmptyProject,
    createProjectFromText: lifecycle.createProjectFromText,
    loadProject: lifecycle.loadProject,
    loadProjectAfterImport: lifecycle.loadProjectAfterImport,
    refreshCurrentProject: lifecycle.refreshCurrentProject,
    restoreEditorFromEditLog: lifecycle.restoreEditorFromEditLog,
    openFile: lifecycle.openFile,
    openLastEditorWorkspace: lifecycle.openLastEditorWorkspace,
    closeFile: lifecycle.closeFile,
    closeProject: lifecycle.closeProject,
    runTranscribe: lifecycle.runTranscribe,
    cancelTranscribe: lifecycle.cancelTranscribe,
    transcribeStartDialogOpen: lifecycle.transcribeStartDialogOpen,
    transcribeStartHasExistingText: lifecycle.transcribeStartHasExistingText,
    confirmTranscribeStart: lifecycle.confirmTranscribeStart,
    cancelTranscribeStart: lifecycle.cancelTranscribeStart,
    saveSegments: lifecycle.saveSegments,
    confirmSegmentEditAndAdvance: lifecycle.confirmSegmentEditAndAdvance,
    markSegmentFinalized: lifecycle.markSegmentFinalized,
    canConfirmSegmentEdit: lifecycle.canConfirmSegmentEdit,
    getSavedSnapshot: lifecycle.getSavedSnapshot,
    editorSpansForText: lifecycle.editorSpansForText,
    editorCorrectPopover: lifecycle.editorCorrectPopover,
    editorCorrectPopoverSuggestions: lifecycle.editorCorrectPopoverSuggestions,
    openEditorCorrectPopover: lifecycle.openEditorCorrectPopover,
    closeEditorCorrectPopover: lifecycle.closeEditorCorrectPopover,
    applyEditorInlineCorrection: lifecycle.applyEditorInlineCorrection,
    autoSaveFooterStatus: lifecycle.autoSaveFooterStatus,
    deleteProject: lifecycle.deleteProject,
    exportTxt: lifecycle.exportTxt,
    exportSrt: lifecycle.exportSrt,
    exportDocx: lifecycle.exportDocx,
    exportDeliveryDocx: lifecycle.exportDeliveryDocx,
    exportDiagnosticBundle: lifecycle.exportDiagnosticBundle,
    exportProjectBundle: lifecycle.exportProjectBundle,
    importProjectBundle: lifecycle.importProjectBundle,
    openAppDataFolder: lifecycle.openAppDataFolder,
    applyDetail: lifecycle.applyDetail,

    // Segment mutations
    undo: lifecycle.undo,
    redo: lifecycle.redo,
    updateSegmentText: lifecycle.updateSegmentText,
    updateSegmentTime: lifecycle.updateSegmentTime,
    updateSegmentBounds: lifecycle.updateSegmentBounds,
    splitAtSelection: lifecycle.splitAtSelection,
    splitAtPlayhead: lifecycle.splitAtPlayhead,
    mergeWithNext: lifecycle.mergeWithNext,
    mergeWithPrev: lifecycle.mergeWithPrev,
    mergeWithNextAt: lifecycle.mergeWithNextAt,
    mergeWithPrevAt: lifecycle.mergeWithPrevAt,
    mergeSegmentRange: lifecycle.mergeSegmentRange,
    deleteSegmentAt: lifecycle.deleteSegmentAt,
    requestDeleteSelection: lifecycle.requestDeleteSelection,
    requestDeleteSelectedIndices: lifecycle.requestDeleteSelectedIndices,
    pendingDeleteCount: lifecycle.pendingDeleteCount,
    selectionLo: lifecycle.selectionLo,
    selectionHi: lifecycle.selectionHi,
    selectionCount: lifecycle.selectionCount,
    isMultiSegmentSelection: lifecycle.isMultiSegmentSelection,
    isContiguousSelection: lifecycle.isContiguousSelection,
    selectedIndices: lifecycle.selectedIndices,
    selectedIndicesArray: lifecycle.selectedIndicesArray,
    isIndexInSelection: lifecycle.isIndexInSelection,
    selectSegmentAt: lifecycle.selectSegmentAt,
    selectSegmentRange: lifecycle.selectSegmentRange,
    selectSegmentIndices: lifecycle.selectSegmentIndices,
    clearMultiSelection: lifecycle.clearMultiSelection,
    segmentDeleteConfirmOpen: lifecycle.segmentDeleteConfirmOpen,
    confirmDeleteSegment: lifecycle.confirmDeleteSegment,
    cancelDeleteSegment: lifecycle.cancelDeleteSegment,
    insertSegmentAfter: lifecycle.insertSegmentAfter,
    insertSegmentFromTimeRange: lifecycle.insertSegmentFromTimeRange,
    flushSegmentTextDrafts: lifecycle.flushSegmentTextDrafts,
    canFindReplace: lifecycle.canFindReplace,
    findReplaceBlockReason: lifecycle.findReplaceBlockReason,
    findReplaceDialog: lifecycle.findReplaceDialog,
    openFindReplace: lifecycle.openFindReplace,
    triggerFindReplaceShortcut: lifecycle.triggerFindReplaceShortcut,
    closeFindReplace: lifecycle.closeFindReplace,
    setFindReplaceFindText: lifecycle.setFindReplaceFindText,
    setFindReplaceReplaceText: lifecycle.setFindReplaceReplaceText,
    findReplaceRunSearch: lifecycle.findReplaceRunSearch,
    findReplaceSelectMatch: lifecycle.findReplaceSelectMatch,
    findReplaceGoNext: lifecycle.findReplaceGoNext,
    findReplaceGoPrev: lifecycle.findReplaceGoPrev,
    findReplaceCurrent: lifecycle.findReplaceCurrent,
    findReplaceRequestReplaceAll: lifecycle.findReplaceRequestReplaceAll,
    findReplaceConfirmReplaceAll: lifecycle.findReplaceConfirmReplaceAll,
    findReplaceCancelReplaceAllPreview: lifecycle.findReplaceCancelReplaceAllPreview,
    findReplaceEditorHighlight: lifecycle.findReplaceEditorHighlight,
    findReplaceReplaceAndNext: lifecycle.findReplaceReplaceAndNext,
    canApplyCorrectionRules: lifecycle.canApplyCorrectionRules,
    correctionRulesBlockReason: lifecycle.correctionRulesBlockReason,
    correctionRulesDialog: lifecycle.correctionRulesDialog,
    requestCorrectionRules: lifecycle.requestCorrectionRules,
    requestPostTranscribeProcessing: lifecycle.requestPostTranscribeProcessing,
    openCorrectionRulesManual: lifecycle.openCorrectionRulesManual,
    correctionRulesStableConflictMessage: lifecycle.correctionRulesStableConflictMessage,
    confirmCorrectionRulesWriteback: lifecycle.confirmCorrectionRulesWriteback,
    toggleCorrectionRulesSegment: lifecycle.toggleCorrectionRulesSegment,
    focusCorrectionRulesPreviewSegment: lifecycle.focusCorrectionRulesPreviewSegment,
    correctionRulesEditorHighlight: lifecycle.correctionRulesEditorHighlight,
    cancelCorrectionRules: lifecycle.cancelCorrectionRules,
    closeCorrectionRulesEmpty: lifecycle.closeCorrectionRulesEmpty,
    canOfferPostTranscribeStageB: lifecycle.canOfferPostTranscribeStageB,
    postTranscribeStageBBlockReason: lifecycle.postTranscribeStageBBlockReason,
    postTranscribeStageBDialog: lifecycle.postTranscribeStageBDialog,
    openPostTranscribeStageB: lifecycle.openPostTranscribeStageB,
    confirmPostTranscribeStageBConsent: lifecycle.confirmPostTranscribeStageBConsent,
    confirmPostTranscribeStageBWriteback: lifecycle.confirmPostTranscribeStageBWriteback,
    togglePostTranscribeStageBSegment: lifecycle.togglePostTranscribeStageBSegment,
    focusPostTranscribeStageBSegment: lifecycle.focusPostTranscribeStageBSegment,
    postTranscribeStageBPreviewFocusSegmentIdx: lifecycle.postTranscribeStageBPreviewFocusSegmentIdx,
    cancelPostTranscribeStageB: lifecycle.cancelPostTranscribeStageB,
    glossaryLearnDialog: lifecycle.glossaryLearnDialog,
    dismissGlossaryLearnPrompt: lifecycle.dismissGlossaryLearnPrompt,
    confirmAddToGlossary: lifecycle.confirmAddToGlossary,
    closeGlossaryLearnPrompt: lifecycle.closeGlossaryLearnPrompt,
    manualCorrectionMemoryDialog: lifecycle.manualCorrectionMemoryDialog,
    openManualCorrectionMemoryDialog: lifecycle.openManualCorrectionMemoryDialog,
    closeManualCorrectionMemoryDialog: lifecycle.closeManualCorrectionMemoryDialog,
    setManualCorrectionRight: lifecycle.setManualCorrectionRight,
    setManualCorrectionAlsoGlossary: lifecycle.setManualCorrectionAlsoGlossary,
    confirmManualCorrectionMemory: lifecycle.confirmManualCorrectionMemory,
    bumpLlmRuntimeChanged: lifecycle.bumpLlmRuntimeChanged,
    closeGateOpen: lifecycle.closeGateOpen,
    closeGateIntent: lifecycle.closeGateIntent,
    stayAfterCloseAttempt: lifecycle.stayAfterCloseAttempt,
    discardUnsavedAndClose: lifecycle.discardUnsavedAndClose,
    saveAndClose: lifecycle.saveAndClose,
    duplicateImportConfirmOpen: lifecycle.duplicateImportConfirmOpen,
    duplicateImportChecking: lifecycle.duplicateImportChecking,
    duplicateImportCheck: lifecycle.duplicateImportCheck,
    cancelDuplicateImport: lifecycle.cancelDuplicateImport,
    openExistingDuplicateImport: lifecycle.openExistingDuplicateImport,
    confirmDuplicateImportCopy: lifecycle.confirmDuplicateImportCopy,
    importFileToProject: lifecycle.importFileToProject,
    pickAndImportFileToProject: lifecycle.pickAndImportFileToProject,
    transcribeNavBlockOpen: lifecycle.transcribeNavBlockOpen,
    cancelTranscribeNavBlock: lifecycle.cancelTranscribeNavBlock,
    confirmTranscribeNavBlock: lifecycle.confirmTranscribeNavBlock,
    hasUnsavedFileEdits: lifecycle.hasUnsavedFileEdits,
    renamingProjectFileId: lifecycle.renamingProjectFileId,
    renameProjectFileDraft: lifecycle.renameProjectFileDraft,
    setRenameProjectFileDraft: lifecycle.setRenameProjectFileDraft,
    beginRenameProjectFile: lifecycle.beginRenameProjectFile,
    cancelRenameProjectFile: lifecycle.cancelRenameProjectFile,
    commitRenameProjectFile: lifecycle.commitRenameProjectFile,
    pendingProjectFileDelete: lifecycle.pendingProjectFileDelete,
    requestDeleteProjectFile: lifecycle.requestDeleteProjectFile,
    cancelDeleteProjectFile: lifecycle.cancelDeleteProjectFile,
    confirmDeleteProjectFile: lifecycle.confirmDeleteProjectFile,
    isRenamingProject: lifecycle.isRenamingProject,
    renameProjectDraft: lifecycle.renameProjectDraft,
    setRenameProjectDraft: lifecycle.setRenameProjectDraft,
    beginRenameProject: lifecycle.beginRenameProject,
    cancelRenameProject: lifecycle.cancelRenameProject,
    commitRenameProject: lifecycle.commitRenameProject,
    projectMetadataDialogOpen: lifecycle.projectMetadataDialogOpen,
    projectMetadataAfterCreate: lifecycle.projectMetadataAfterCreate,
    openProjectMetadataDialog: lifecycle.openProjectMetadataDialog,
    closeProjectMetadataDialog: lifecycle.closeProjectMetadataDialog,
    saveProjectMetadata: lifecycle.saveProjectMetadata,
    pendingProjectDelete: lifecycle.pendingProjectDelete,
    requestDeleteProject: lifecycle.requestDeleteProject,
    cancelDeleteProject: lifecycle.cancelDeleteProject,
    confirmDeleteProject: lifecycle.confirmDeleteProject,
    segmentAnnotationDialog: lifecycle.segmentAnnotationDialog,
    segmentAnnotationSaving: lifecycle.segmentAnnotationSaving,
    openSegmentAnnotationDialog: lifecycle.openSegmentAnnotationDialog,
    closeSegmentAnnotationDialog: lifecycle.closeSegmentAnnotationDialog,
    setSegmentAnnotationDraft: lifecycle.setSegmentAnnotationDraft,
    saveSegmentAnnotation: lifecycle.saveSegmentAnnotation,
    clearSegmentAnnotation: lifecycle.clearSegmentAnnotation,

    // ASR bridge
    asrHealth: asr.asrHealth,
    asrHealthDetail: asr.asrHealthDetail,
    asrPresentation: asr.asrPresentation,
    bundledAsrDiag: asr.bundledAsrDiag,
    asrCaps: asr.asrCaps,
    asrModelCacheInfo: asr.asrModelCacheInfo,
    waveformPeaksCacheInfo: asr.waveformPeaksCacheInfo,
    asrModelCacheBusy: asr.asrModelCacheBusy,
    asrCacheMessage: asr.asrCacheMessage,
    sttOnlineBridgeReady: asr.sttOnlineBridgeReady,
    funasrInstallMessage: asr.funasrInstallMessage,
    prepareModelBusy: asr.prepareModelBusy,
    prepareModelCancelling: asr.prepareModelCancelling,
    prepareModelProgress: asr.prepareModelProgress,
    prepareModelFailure: asr.prepareModelFailure,
    prepareDefaultFunasrModel: asr.prepareDefaultFunasrModel,
    cancelPrepareModel: asr.cancelPrepareModel,
    localAsrModelCatalog: asr.localAsrModelCatalog,
    refreshAsrModelCacheInfo: asr.refreshAsrModelCacheInfo,
    clearAsrModelCache: asr.clearAsrModelCache,
    clearOrphanWaveformPeaksCache: asr.clearOrphanWaveformPeaksCache,
    retryBundledAsrSidecar: asr.retryBundledAsrSidecar,
    refreshAsrHealth: asr.refreshAsrHealth,
    installFunasrDepsInteractive: asr.installFunasrDepsInteractive,
    copyFunasrManualCommands: asr.copyFunasrManualCommands,
    bumpSttOnlineRuntimeChanged: asr.bumpSttOnlineRuntimeChanged,
    asrSetup,
  };
}
