export const DEFAULT_FONT_OPTIONS = ["PingFang SC", "Songti SC", "Hiragino Sans GB", "Inter", "Noto Sans CJK SC"];

export const TRANSCRIPT_META_WIDTH_STORAGE_KEY = "rushi.editor.transcript.metaWidthPx";
export const TRANSCRIPT_META_WIDTH_MIN = 104;
export const TRANSCRIPT_META_WIDTH_MAX = 260;

export const SYSTEM_FONT_CANDIDATES = [
  "PingFang SC",
  "PingFang TC",
  "PingFang HK",
  "Songti SC",
  "Songti TC",
  "Heiti SC",
  "Heiti TC",
  "Kaiti SC",
  "Kaiti TC",
  "STSong",
  "STHeiti",
  "STKaiti",
  "STFangsong",
  "Hiragino Sans GB",
  "Hiragino Sans CNS",
  "Hiragino Mincho ProN",
  "Noto Sans CJK SC",
  "Noto Sans SC",
  "Noto Sans TC",
  "Noto Sans HK",
  "Noto Sans JP",
  "Noto Serif SC",
  "Noto Serif TC",
  "Noto Serif JP",
  "Source Han Sans SC",
  "Source Han Sans CN",
  "Source Han Sans TC",
  "Source Han Sans",
  "Source Han Serif SC",
  "Source Han Serif CN",
  "Source Han Serif TC",
  "Source Han Serif",
  "LXGW WenKai",
  "Smiley Sans",
  "Alibaba PuHuiTi",
  "HarmonyOS Sans SC",
  "MiSans",
  "OPPOSans",
  "Segoe UI",
  "Microsoft YaHei",
  "SimSun",
  "SimHei",
  "NSimSun",
  "FangSong",
  "KaiTi",
  "Arial",
  "Helvetica Neue",
  "SF Pro Text",
  "SF Pro Display",
  "Avenir Next",
  "Times New Roman",
  "Georgia",
  "Menlo",
  "Monaco",
  "JetBrains Mono",
  "Fira Code",
  "Inter",
] as const;

export function normalizeFontFamily(raw: string): string {
  return raw.replace(/^"+|"+$/g, "").replace(/^'+|'+$/g, "").trim();
}
