#!/usr/bin/env bash
# Rebuild requirements-sidecar-cuda-win_amd64.lock non-torch section from CPU lock + fixed cu126 torch triple.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASR="$ROOT/services/asr"
CPU="$ASR/requirements-sidecar-cpu-macos-arm64.lock"
OUT="$ASR/requirements-sidecar-cuda-win_amd64.lock"

grep -E '^(torch|torchvision|torchaudio)==' "$CPU" | head -3

{
  cat <<'HDR'
# Windows x64 CUDA PyTorch + same FunASR transitive stack as CPU lock (minus torch family).
# Regenerated by scripts/regen-sidecar-cuda-win-lock.sh after CPU lock changes.
# Python 3.12. Install on Windows: pip install -r requirements-sidecar-cuda-win_amd64.lock
#
# Torch: cu126 + cp312 + win_amd64 (verify on download.pytorch.org if bumping).
#
--extra-index-url https://download.pytorch.org/whl/cu126
--extra-index-url https://pypi.org/simple/

torch==2.11.0+cu126
torchvision==0.26.0+cu126
torchaudio==2.11.0+cu126

HDR
  grep -v '^[[:space:]]*#' "$CPU" | grep -v '^--' | grep -viE '^(torch|torchvision|torchaudio)==' | LC_ALL=C sort
} > "$OUT"

echo "Wrote $OUT"
