#!/usr/bin/env bash
# Regenerate services/asr/requirements-sidecar-cpu-macos-arm64.lock from current services/asr sources.
# Run on macOS (arm64 or x86_64) with Python 3.12 + network. Requires: bash, python3.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASR="$ROOT/services/asr"
OUT="$ASR/requirements-sidecar-cpu-macos-arm64.lock"
cd "$ASR"

rm -rf .venv-lockgen-cpu
python3 -m venv .venv-lockgen-cpu
# shellcheck source=/dev/null
source .venv-lockgen-cpu/bin/activate
python -m pip install -U pip setuptools wheel
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
python -m pip install -e ".[funasr]"

{
  cat <<'HDR'
# CPU + MPS PyTorch + FunASR stack for PyInstaller ASR sidecar (CPU/MPS variant).
# Regenerated by scripts/regen-sidecar-cpu-lock.sh — edit that script, not hand-edit pins.
# rushi-asr is installed editable here for resolution only; PyInstaller bundles sources separately.
#
# Install (sidecar build venv):
#   pip install -r requirements-sidecar-cpu-macos-arm64.lock
#
# Other platforms: see requirements-sidecar-cpu-macos-x86_64.lock / requirements-sidecar-cpu-win_amd64.lock / requirements-sidecar-cpu-linux_x86_64.lock
#
--index-url https://download.pytorch.org/whl/cpu
--extra-index-url https://pypi.org/simple/

HDR
  pip freeze | grep -vi '^-e ' | grep -vi '^#' | grep -vi '^rushi-asr' | LC_ALL=C sort
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines). Next: refresh requirements-sidecar-cuda-win_amd64.lock torch lines if torch family bumped."
