#!/usr/bin/env bash
# Regenerate services/asr/requirements-sidecar-cpu-macos-arm64.lock from current services/asr sources.
# Run on macOS (arm64 or x86_64) with Python 3.12 + network. Requires: bash, python3.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ASR="$ROOT/services/asr"
OUT="$ASR/requirements-sidecar-cpu-macos-arm64.lock"
cd "$ASR"

rm -rf .venv-lockgen-cpu
python3 -m venv .venv-lockgen-cpu
# shellcheck source=/dev/null
source .venv-lockgen-cpu/bin/activate
python -m pip install -U pip setuptools wheel
python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
python -m pip install -e ".[funasr]"
# Floor pins for known CVEs (pip-audit): pillow PYSEC-2026-* · setuptools PYSEC-2026-3447.
# Note: as of 2026-07, PyTorch CPU index may ship torch 2.13 with torchaudio still at 2.11 — accept that skew.
python -m pip install "pillow>=12.3.0" "setuptools>=83.0.0"
python -c 'import torch,torchvision,torchaudio,PIL,setuptools; print("torch",torch.__version__,"tv",torchvision.__version__,"ta",torchaudio.__version__,"pillow",PIL.__version__,"setuptools",setuptools.__version__)'


{
  cat <<'HDR'
# CPU + MPS PyTorch + FunASR stack for PyInstaller ASR sidecar (CPU/MPS variant).
# Regenerated by scripts/regen-sidecar-cpu-lock.sh — edit that script, not hand-edit pins.
# rushi-asr is installed editable here for resolution only; PyInstaller bundles sources separately.
#
# Install (sidecar build venv):
#   pip install -r requirements-sidecar-cpu-macos-arm64.lock
#
# Other platforms: see requirements-sidecar-cpu-macos-x86_64.lock / requirements-sidecar-cpu-win_amd64.lock / requirements-sidecar-cpu-linux_x86_64.lock
#
--index-url https://download.pytorch.org/whl/cpu
--extra-index-url https://pypi.org/simple/

HDR
  pip freeze \
    | grep -vi '^-e ' \
    | grep -vi '^#' \
    | grep -vi '^rushi-asr' \
    | sed "s/^\(uvloop==.*\)$/\1; sys_platform != 'win32'/" \
    | LC_ALL=C sort
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines). Next: refresh requirements-sidecar-cuda-win_amd64.lock torch lines if torch family bumped."
