/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  /** 与既有 App.css 共存：不注入 Tailwind Preflight，避免全局 reset 冲掉壳层样式 */
  corePlugins: {
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        /** Clay.com DESIGN.md：暖画布 canvas、近黑主 CTA、饱和 accent 见 clay-* */
        "zen-ink": "#0a0a0a",
        "zen-paper": "#fffaf0",
        "zen-saffron": "#0a0a0a",
        "zen-saffron-light": "#e5e5e5",
        "zen-saffron-mid": "#1f1f1f",
        "zen-saffron-deep": "#0a0a0a",
        "zen-ochre": "#faf5e8",
        "zen-stone": "#6a6a6a",
        "zen-cinnabar": "#ef4444",
        "zen-indigo": "#1a3a3a",
        "zen-success": "#22c55e",
        "zen-gray-200": "#ebe6d6",
        "zen-gray-300": "#e5e5e5",
        "zen-gray-400": "#9a9a9a",
        "zen-gray-500": "#6a6a6a",
        "clay-pink": "#ff4d8b",
        "clay-teal": "#1a3a3a",
        "clay-lavender": "#b8a4ed",
        "clay-peach": "#ffb084",
        "clay-ochre": "#e8b94a",
        "clay-mint": "#a4d4c5",
        "clay-coral": "#ff6b5a",
        "clay-card": "#f5f0e0",
        "app-bg": "#fffaf0",
        "app-accent": "#ff4d8b",
        "app-accent-hover": "#e63e7a",
        "app-text-main": "#0a0a0a",
        "app-text-muted": "#6a6a6a",
        "app-highlight": "#f5f0e0",
        /** P1 WaveSurfer（与 src/config/tokens.ts COLORS.p1Waveform* 同源） */
        "zen-wf-surface": "#ffffff",
        "zen-wf-wave": "#c4c4c8",
        "zen-wf-progress": "#8e8e93",
        "zen-wf-cursor": "#6a6a6f",
        "brand-bg": "#fffaf0",
        "brand-orange": "#e8b94a",
        "brand-gray": "#faf5e8",
        "brand-input-border": "#e5e5e5",
        "brand-input-bg": "#fffaf0",
        "brand-secondary-bg": "#faf5e8",
        "brand-secondary-text": "#3a3a3a",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
    },
  },
  plugins: [],
};
