import type { LlmOllamaTone } from "./llmEnvStatusTypes";
import {
  ENV_STATUS_BANNER_TITLE_CLASS,
  ENV_STATUS_DOT_CLASS,
  ENV_STATUS_PANEL_CLASS,
  ENV_STATUS_REFRESH_BTN_BASE,
  ENV_STATUS_REFRESH_BTN_CLASS,
} from "../ui/envStatusTokens";

/** 顶栏芯片 / 设置页能力状态条（`LLM_*` 为历史别名，与 `ENV_*` 同源）。 */
export const LLM_STATUS_DOT_CLASS: Record<LlmOllamaTone, string> = ENV_STATUS_DOT_CLASS;
export const LLM_STATUS_PANEL_CLASS: Record<LlmOllamaTone, string> = ENV_STATUS_PANEL_CLASS;
export const LLM_STATUS_BANNER_TITLE_CLASS: Record<LlmOllamaTone, string> = ENV_STATUS_BANNER_TITLE_CLASS;
export const LLM_STATUS_REFRESH_BTN_BASE = ENV_STATUS_REFRESH_BTN_BASE;
export const LLM_STATUS_REFRESH_BTN_CLASS: Record<LlmOllamaTone, string> = ENV_STATUS_REFRESH_BTN_CLASS;

export {
  ENV_STATUS_BANNER_TITLE_CLASS,
  ENV_STATUS_DOT_CLASS,
  ENV_STATUS_PANEL_CLASS,
  ENV_STATUS_REFRESH_BTN_BASE,
  ENV_STATUS_REFRESH_BTN_CLASS,
};
